name: Run Script TNT Every 6 Hours FR

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create folders
        run: |
          mkdir -p fr
          mkdir -p txt

      - name: Extract TF1 M3U8 and Download
        run: |
          echo "Fetching main page..."

          page=$(curl -k -s -L \
            -H "User-Agent: Mozilla/5.0 (Linux; Android 14)" \
            "https://callofliberty.fr/tv/1-TF1/1-TF1.php")

          echo "Searching for stream URL..."

          url=$(echo "$page" | grep -oE 'https?://[^\"'\'' ]+\.m3u8[^\"'\'' ]*' | head -n 1)

          if [ -z "$url" ]; then
            echo "❌ No m3u8 found!"
            exit 1
          fi

          echo "Found URL: $url"

          echo "Downloading stream..."
          stream=$(curl -k -s -L \
            -e "https://callofliberty.fr/" \
            -H "User-Agent: Mozilla/5.0 (Linux; Android 14)" \
            -H "Origin: https://callofliberty.fr" \
            "$url")

          if [ -z "$stream" ]; then
            echo "❌ Failed to fetch stream content"
            exit 1
          fi

          echo "$stream" > fr/videotf1.m3u8

          echo "✅ Done"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "kada.developers@gmail.com"
          git config --local user.name "kadadevelopers"
          git add fr/*.m3u8
          git commit -m "latest updates" || echo "No changes"
          git push
