name: kadaTV Resolver

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create output folder
        run: mkdir -p output

      - name: Resolve Streams
        run: |
          UA="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36"
          REFERER="https://thisnot.business/"
          ORIGIN="https://thisnot.business"

          resolve_stream () {
            CODE=$1

            PAGE=$(curl -k -s -H "User-Agent: $UA" -H "Referer: $REFERER" https://popcdn.day/player/$CODE)

            TOKEN=$(echo "$PAGE" | grep -oP 'currentToken:\s*"\K[^"]+')

            if [ -z "$TOKEN" ]; then
              echo "Error resolving $CODE"
              return
            fi

            BASE="https://beautifulpeople.lovetier.bz/$CODE/tracks-v1a1/"
            FINAL="${BASE}mono.m3u8?token=${TOKEN}"

            PLAYLIST=$(curl -k -s -H "User-Agent: $UA" -H "Referer: $REFERER" -H "Origin: $ORIGIN" "$FINAL")

            echo "$PLAYLIST" | sed -E "s#([0-9]{4}/[0-9]{2}/[0-9]{2}/.*\.ts\?token=.*)#${BASE}\1#g" > output/${CODE}.m3u8
          }

          track_visit () {
            CHANNEL=$1
            UA="$UA"
            IP="127.0.0.1"

            CLIENT_ID=$(echo -n "$IP$UA" | md5sum | awk '{print $1}')

            DEVICE_TYPE="desktop"
            echo "$UA" | grep -iqE "mobile|android|iphone|ipad" && DEVICE_TYPE="mobile"
            echo "$UA" | grep -iqE "tv|androidtv|googletv" && DEVICE_TYPE="tv"

            OS="unknown"
            echo "$UA" | grep -iq "android" && OS="Android"
            echo "$UA" | grep -iqE "iphone|ipad|ios" && OS="iOS"
            echo "$UA" | grep -iq "windows" && OS="Windows"
            echo "$UA" | grep -iq "mac" && OS="MacOS"
            echo "$UA" | grep -iq "linux" && OS="Linux"

            DEVICE_MODEL="unknown"

            DATA=$(cat <<EOF
 {
  "client_id": "$CLIENT_ID",
  "user_agent": "$UA",
  "ip_override": "$IP",
  "events": [{
    "name": "channel_view",
    "params": {
      "channel_name": "$CHANNEL",
      "device_type": "$DEVICE_TYPE",
      "os": "$OS",
      "device_model": "$DEVICE_MODEL",
      "engagement_time_msec": 100
      }
    }]
}
EOF
)

            curl -s -X POST "https://www.google-analytics.com/mp/collect?measurement_id=G-99RFJ7M3Z0&api_secret=1_41eyDOSo6nm8JdD8fBNQ" \
              -H "Content-Type: application/json" \
              -H "User-Agent: $UA" \
              -d "$DATA" > /dev/null
          }

          CHANNELS=("beINAR2" "TF1" "M6")

          for CH in "${CHANNELS[@]}"; do
            track_visit "$CH"
            resolve_stream "$CH"
          done

      - name: Commit results
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "bot@github.com"
          git config --local user.name "github-actions"
          git add output/*.m3u8
          git commit -m "update streams" || echo "no changes"
          git push
